import { StyleSheet } from "react-native";
export const styles = StyleSheet.create( 
    {  
        mainContainer:{  
            flex:1,
            backgroundColor: '#f1f1f1',
        },  
        container:{  
            flex:0.31,
            backgroundColor:'white',
            justifyContent:'center',
            alignItems:'center',
        },
        cardView:{
            width:150,
            height:150,
            backgroundColor:'#3696ec',
            padding:2,
        },
        cardContainer:{
            flex:1,
            backgroundColor:'white',
            borderRadius:7,
            justifyContent:'center',
            alignItems:'center',
            flexDirection:'column',
        },
        imageView:{
            width:100,
            height:100,
            backgroundColor:'white',
            borderRadius:50,
        },
        textView:{
            width:'80%',
            height:25,
        },
        imageContent:{
            width:100,
            height:100,
        },
        textContent:{
            fontWeight:'bold',
            color:'gray',
            textAlign:'center',
        },
        footerContainer:{  
            flex:0.07,
            backgroundColor:'#e8e4c9',
            justifyContent:'center',
            alignItems:'center',
            flexDirection:'row',
        },
        footerView:{
            color:'black',
            fontWeight:'bold',
        },
        logoContainer:{
            paddingLeft:10,
        },
        logoContent:{
            width:40,
            height:40,
            borderRadius:50,
            borderColor:'black',
            borderWidth:1,
        }
    }
);